"""add signin model

Revision ID: 00fa84d729da
Revises: e0aa49b77bc8
Create Date: 2024-08-12 06:27:47.205821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '00fa84d729da'
down_revision = 'e0aa49b77bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('confirm_password', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signin')
    # ### end Alembic commands ###
