"""Add Instructor model using foreign key to Register model

Revision ID: 0997546acfdd
Revises: 7d0a74c84f2a
Create Date: 2025-07-04 15:49:00.371037

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0997546acfdd'
down_revision = '7d0a74c84f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verification_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verification_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verify_on', sa.Date(), nullable=False),
    sa.Column('register_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructor')
    # ### end Alembic commands ###
