"""add vendorfrom model

Revision ID: 3ad0e09f49c9
Revises: 00fa84d729da
Create Date: 2024-08-12 10:23:48.956635

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3ad0e09f49c9'
down_revision = '00fa84d729da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendorform',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendorform')
    # ### end Alembic commands ###
