"""Add qualification model

Revision ID: 6285bb8ae98f
Revises: 7668c965d401
Create Date: 2025-08-01 14:55:07.590196

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6285bb8ae98f'
down_revision = '7668c965d401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('degree_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_period', sa.DateTime(), nullable=False),
    sa.Column('verification_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified_on', sa.DateTime(), nullable=False),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualification')
    # ### end Alembic commands ###
