"""added address and contact_no

Revision ID: a626014c555c
Revises: 3ad0e09f49c9
Create Date: 2024-08-12 12:13:35.795313

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a626014c555c'
down_revision = '3ad0e09f49c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'contact_no')
    op.drop_column('item', 'address')
    # ### end Alembic commands ###
