"""Add experience table model

Revision ID: d2663cd437c2
Revises: d831ddc6b1de
Create Date: 2025-07-09 17:58:38.685910

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd2663cd437c2'
down_revision = 'd831ddc6b1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_period', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('verification_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('verified_on', sa.DateTime(), nullable=False),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    # ### end Alembic commands ###
