"""added all models

Revision ID: d31d2e7eb303
Revises: 1a31ce608336
Create Date: 2024-08-14 06:40:37.697330

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd31d2e7eb303'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('students', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('confirm_password', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_usn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_usn')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('pin_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendorform',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'contact_no')
    op.drop_column('item', 'address')
    op.drop_table('vendorform')
    op.drop_table('vendor')
    op.drop_table('students')
    op.drop_table('signin')
    op.drop_table('college')
    # ### end Alembic commands ###
