"""Add user login logs

Revision ID: d40abe465978
Revises: 2bb42aba2565
Create Date: 2025-08-08 15:12:46.321670

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd40abe465978'
down_revision = '2bb42aba2565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userloginlogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('register_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userloginlogs')
    # ### end Alembic commands ###
