"""Add bank details model

Revision ID: d831ddc6b1de
Revises: 0997546acfdd
Create Date: 2025-07-05 15:07:06.183594

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd831ddc6b1de'
down_revision = '0997546acfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankdetails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_holder_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upi_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ifsc_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('register_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_no'),
    sa.UniqueConstraint('ifsc_code'),
    sa.UniqueConstraint('upi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankdetails')
    # ### end Alembic commands ###
