"""Add student table

Revision ID: e0aa49b77bc8
Revises: e425da487573
Create Date: 2024-08-08 13:52:20.472882

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e0aa49b77bc8'
down_revision = 'e425da487573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_usn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_usn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
